local ParkourConfig = {
    Vault = {
        MAX_VAULT_HEIGHT = 4,
        BUFFER_CHECK = 3,
        MIN_VAULT_DISTANCE = 4,
        MAX_VAULT_DISTANCE = 15,
        MIN_VAULT_SPEED = 25,
        VAULT_DURATION = 0.3
    },

    Momentum = {
        MIN_MOVE_SPEED = 12,
        MAX_MOMENTUM = 100,
        MIN_MOMENTUM = 0,
        MAX_RISING_MOMENTUM = 10,
        STARTUP_MOMENTUM = 10,
        SPRINT_MOMENTUM = 90
    }


}

return ParkourConfig